package net.themonhub.playeranimationfeatures

object FunnyStartup {
    private val messages: List<String> = listOf(
        "TheMonHub was here... or maybe not",
        "AAAAAAAAAAAAAA",
        "Furry is cool!",
        "Beep beep boop",
        "Something something smh",
        "This is a virus.",
        "Furry rules the world!",
        "!!! Cats > Dogs !!!",
        "Rykou is the badest boy in the world!",
        "*Bites Rykou*",
        "*Mauls Rykou*",
        "*Explodes Rykou*",
        "*Implodes Rykou*",
        "Bad boy",
        "Good boy",
        "I hate bibi",
        "Whoever reads this is a furry :3",
        "I CAST FURRIFICATION!",
        "Pedo begone!",
        "To be honest, I'm not sure what to say here.",
        "This is funny, isn't it?",
        "Animations animations animations",
        "Crazy? I was crazy once...",
        "Just laugh at this message",
        "I'm not a furry, I'm a cat",
        "Who would've known that you need to use hot water instead of cold water for a tea?",
        "Coffee sucks",
        "Tea sucks",
        "Dogs sucks",
        "You got hacked!",
        "Your IP is: 127.0.0.1",
        "Hey guys! I built my website! type in localhost",
        "AI will take over the world!",
        "Does anyone actually read these?",
        "🐟",
        "😺",
        "😼",
        "They're turning the frogs gay!",
        "Your dad is a furry",
        "Your mom is a furry",
        "Oh no, you found the secret message! Now you have to subscribe to TheMonHub on YouTube and Twitch!",
        "Whoever reads this is gay",
        "*Kill everyone*",
        "Sorry Dave, I'm afraid I can't do that",
        "Look at you reading the logs!",
        "Aniiimaaatioooon",
        "Smh my head",
        "Mau Makan Apa?",
        "OH MY GOD!!",
        "RELAX! I'm just looking for Gix Busok.",
        "Slenderman is waiting",
        "The cake is a lie.",
        "My attacks have no effect on you? Who decided that?",
        "Domain Expansion",
        "Somebody gotta read this someday",
        "I don't know what to say here, so have a random message instead",
        "This is very funny, isn't it?",
        "It works... I believe?",
        "Hacking your computer...",
        "Forever with you, my friend.",
        "Besto Friendo!",
        "Let me just teleport the bread...",
        "I just put a fork in my microwave.",
        "WARNING: Very silly!",
        "Can I haz cheeseburger?",
        "Please give me 5 more minutes...",
        ":3",
        ":O",
        ">:3c",
        ">:O",
        ">:3",
        "UwU",
        "OwO",
        "Owo",
        "Owo what's this?",
        "I just wanted to say hi!",
        "I hope you have a great day!",
        "Don't forget to smile :)",
        "If you're reading this, you're awesome!",
        "This is a random message, but I hope it made you smile!",
        "Remember to take breaks and stay hydrated!",
        "You're doing great, keep it up!",
        "I can't believe you read this far!",
        "Congratulations, you found the secret message!",
        "This is the end of the messages, but I hope you enjoyed them!"
    )
    fun printFunnyStartupMessage() {
        PlayerAnimationFeatures.logger.info(messages.random())
    }
}